import type { TourConfig } from "@/features/learning/types";
import { getModule } from "@/shared/lib/curriculum";
import { fillInput } from "@/shared/lib/tour-utils";

const HOME = "/";
const mod = getModule("oms-client")!;

export const ClientsTour: TourConfig = {
  moduleId: "oms-client",
  pageKey: "oms-client",
  pageHref: "/oms/clients",
  parentModuleName: "Clients",
  track: "OMS",
  number: mod.number,
  title: mod.title,
  skills: mod.skills,
  homeHref: HOME,
  glossaryKeys: [
    "Client",
    "PAN No.",
    "Mark as Perishable",
    "Pack Box Attributes",
    "Primary Routing Algorithm",
    "Minimize Distance",
    "Minimize Shipments",
    "Secondary Allocation Method",
    "Linked Parties",
  ],
  pitfalls: [
    "Creating suppliers, customers or locations before the client exists",
    "Submitting without PAN — it is mandatory",
    "Marking a non-expiry brand as perishable",
    "Leaving the default routing algorithm when the brand needs nearest-location delivery",
  ],
  scenarios: [
    {
      id: "abc-fashion",
      title: "Onboard ABC Fashion",
      story:
        "ABC Fashion is going live on Omni. Create the client, then switch its routing from the default Minimize Shipments to Minimize Distance so orders ship from the nearest location.",
    },
  ],
  summary: {
    title: "Client Creation & Routing — complete",
    intro: "You created a client in OMS and configured how its orders are routed to a fulfillment location.",
    takeaways: [
      "Client creation is the first master setup step — everything else hangs off it",
      "Name, PAN, Contact Name and the address fields are mandatory",
      "Perishable and Pack Box Attributes are client-level behaviour flags",
      "A new client defaults to Minimize Shipments until you configure it",
    ],
    recap: [
      "Minimize Distance = nearest location with stock → faster, cheaper delivery",
      "Minimize Shipments = one location covering the most items → fewer parcels",
      "Secondary Allocation is the fallback when the primary location is short",
      "Next: suppliers, customers, then fulfillment locations",
    ],
  },
  quiz: [
    {
      question: "Which field is mandatory when creating a client?",
      choices: ["Contact Email", "PAN No.", "Area", "Address Line 2"],
      answer: 1,
      explain: "PAN No. is mandatory at client creation; email, area and address line 2 are optional.",
    },
    {
      question: "Mark as Perishable should be enabled when…",
      choices: [
        "The client ships internationally",
        "The client has many warehouses",
        "The client's products have expiry or shelf life",
        "The client wants fewer parcels",
      ],
      answer: 2,
      explain: "It switches on batch/expiry handling for food, cosmetics, medicines and similar goods.",
    },
    {
      question: "A customer in Pune orders 3 items. Mumbai has 2 of 3, Delhi has all 3. Under Minimize Shipments, OMS picks…",
      choices: ["Mumbai, it is nearer", "Delhi, it can send one parcel", "Both, split the order", "Neither, the order fails"],
      answer: 1,
      explain: "Minimize Shipments favours the location that fulfils the most items together, even if it is farther.",
    },
    {
      question: "A brand wants the fastest possible delivery. Which algorithm fits?",
      choices: ["Minimize Shipments", "Minimize Distance", "Primary and Secondary", "Mark as Perishable"],
      answer: 1,
      explain: "Minimize Distance ships from the nearest location holding stock, cutting delivery time and SLA risk.",
    },
    {
      question: "Secondary Allocation Method is used when…",
      choices: [
        "The primary location cannot fulfil the whole order",
        "The client is perishable",
        "PAN is missing",
        "A manifest is closed",
      ],
      answer: 0,
      explain: "It is the fallback logic — instead of failing the order, OMS can pull the remainder from a mapped secondary location.",
    },
  ],
  steps: [
    {
      element: "#clients-tabs",
      title: "Clients screen",
      description:
        "Two tabs: <strong>Client Details</strong> to create and view clients, <strong>Primary Routing Algorithm</strong> to configure how their orders are routed.",
      expected: { type: "action" },
      onEnter: () => {
        document.getElementById("tab-client-details")?.click();
      },
      skillLabel: "Create",
      skillIndex: 1,
    },
    {
      element: "#clients-btn-add",
      title: "Add Client",
      description: "Opens the client creation form. A client is the brand or business unit that uses Omni.",
      expected: { type: "action" },
      openModalOnNext: "modal-add-client",
      skillLabel: "Create",
      skillIndex: 1,
    },
    {
      element: "#modal-add-client-panel",
      title: "Add New Client",
      description:
        "Everything in OMS — products, suppliers, customers, locations, orders, routing — is stored client-wise, so this is the first master setup step.",
      expected: { type: "action" },
      side: "bottom",
      skillLabel: "Create",
      skillIndex: 1,
    },
    {
      element: "#field-client-name",
      title: "Name *",
      description: "Required. The brand or company name. Example: <strong>ABC Fashion</strong>",
      practicePrompt: "ABC Fashion",
      required: true,
      expected: { type: "input", selector: "#client-name", value: "ABC Fashion" },
      side: "right",
      skillLabel: "Create",
      skillIndex: 1,
    },
    {
      element: "#field-client-pan",
      title: "PAN No. *",
      description: "Required. The client's PAN. Example: <strong>AAACA1234F</strong>",
      practicePrompt: "AAACA1234F",
      required: true,
      commonMistakes: "Submitting without PAN — creation will fail.",
      expected: { type: "input", selector: "#client-pan", value: "AAACA1234F" },
      side: "left",
      skillLabel: "Create",
      skillIndex: 1,
    },
    {
      element: "#field-perishable",
      title: "Mark as Perishable",
      description:
        "Tick this only when the brand sells expiry or shelf-life goods — food, cosmetics, medicines. It switches on batch and expiry handling in GRN and picking. ABC Fashion is apparel, so leave it <strong>off</strong>.",
      expected: { type: "action" },
      commonMistakes: "Marking a non-expiry brand perishable forces needless batch capture on the floor.",
      side: "right",
      skillLabel: "Configure",
      skillIndex: 2,
    },
    {
      element: "#field-pack-box",
      title: "Pack Box Attributes",
      description:
        "Client-level packing rules. Tick what packers must capture per box — dimensions, SKU, or weight. Different brands pack differently, so this lives on the client.",
      expected: { type: "action" },
      side: "right",
      skillLabel: "Configure",
      skillIndex: 2,
    },
    {
      element: "#field-contact-name",
      title: "Contact Name *",
      description: "Required. Who to reach at the brand. Example: <strong>Rajesh Kumar</strong>",
      practicePrompt: "Rajesh Kumar",
      required: true,
      expected: { type: "input", selector: "#client-contact-name", value: "Rajesh Kumar" },
      side: "right",
      skillLabel: "Create",
      skillIndex: 1,
    },
    {
      element: "#field-contact-more",
      title: "Contact Email / Number",
      description:
        "Both optional, but worth filling — this is who OMS support contacts about the client's orders.",
      practicePrompt: "rajesh@abcfashion.in",
      expected: { type: "input", selector: "#client-contact-email", value: "rajesh@abcfashion.in" },
      onWatchFill: () => fillInput("#client-contact-number", "+91-9876543210"),
      side: "left",
      skillLabel: "Create",
      skillIndex: 1,
    },
    {
      element: "#field-address1",
      title: "Address Line 1 *",
      description: "Required. The registered or operational address. Example: <strong>Plot 42, Sector 12</strong>",
      practicePrompt: "Plot 42, Sector 12",
      required: true,
      expected: { type: "input", selector: "#client-address1", value: "Plot 42, Sector 12" },
      side: "right",
      skillLabel: "Create",
      skillIndex: 1,
    },
    {
      element: "#field-city",
      title: "City *",
      description: "Required. Example: <strong>Bengaluru</strong>",
      practicePrompt: "Bengaluru",
      required: true,
      expected: { type: "input", selector: "#client-city", value: "Bengaluru" },
      side: "right",
      skillLabel: "Create",
      skillIndex: 1,
    },
    {
      element: "#field-pincode",
      title: "Pincode *",
      description: "Required. Example: <strong>560066</strong>",
      practicePrompt: "560066",
      required: true,
      expected: { type: "input", selector: "#client-pincode", value: "560066" },
      side: "top",
      skillLabel: "Create",
      skillIndex: 1,
    },
    {
      element: "#field-country",
      title: "Country *",
      description: "Required. Example: <strong>India</strong>",
      practicePrompt: "India",
      required: true,
      expected: { type: "select", selector: "#client-country", value: "IN" },
      side: "left",
      skillLabel: "Create",
      skillIndex: 1,
    },
    {
      element: "#field-state",
      title: "State *",
      description: "Required. Example: <strong>Karnataka</strong>",
      practicePrompt: "Karnataka",
      required: true,
      expected: { type: "select", selector: "#client-state", value: "KA" },
      side: "right",
      skillLabel: "Create",
      skillIndex: 1,
    },
    {
      element: "#modal-add-client-actions",
      title: "Submit",
      description:
        "Creates the client and issues its Client ID. Next we configure how its orders get routed.",
      expected: { type: "action" },
      onWatchFill: () => {
        document.getElementById("client-btn-submit")?.click();
      },
      switchTabOnNext: "#tab-routing-algorithm",
      side: "top",
      skillLabel: "Submit",
      skillIndex: 3,
    },
    {
      element: "#routing-table",
      title: "Default algorithm",
      description:
        "Every new client starts on <strong>MINIMIZE SHIPMENTS</strong> — the system default. ABC Fashion wants fastest delivery, so we will change it.",
      expected: { type: "action" },
      side: "top",
      skillLabel: "Routing",
      skillIndex: 4,
    },
    {
      element: "#routing-row-0",
      title: "Open the client",
      description: "Click the client row to change its Primary Routing Algorithm.",
      expected: { type: "action" },
      openModalOnNext: "modal-routing-algorithm",
      side: "bottom",
      skillLabel: "Routing",
      skillIndex: 4,
    },
    {
      element: "#routing-radios",
      title: "Primary Routing Algorithm",
      description:
        "<strong>Minimize Distance</strong> ships from the nearest location holding stock — faster delivery, lower freight. <strong>Minimize Shipments</strong> favours one location that covers the most items — fewer parcels. Pick <strong>MINIMIZE DISTANCE</strong>.",
      practicePrompt: "MINIMIZE DISTANCE",
      required: true,
      commonMistakes: "Leaving the default when the brand's priority is delivery speed.",
      expected: { type: "radio", name: "client-routing-algo", value: "MINIMIZE DISTANCE" },
      side: "bottom",
      skillLabel: "Routing",
      skillIndex: 4,
    },
    {
      element: "#modal-routing-actions",
      title: "Update",
      description:
        "Saves the routing rule against the client. From here you would add suppliers, customers, then fulfillment locations.",
      expected: { type: "action" },
      onWatchFill: () => {
        document.getElementById("routing-btn-update")?.click();
      },
      side: "top",
      skillLabel: "Routing",
      skillIndex: 4,
    },
  ],
};
