import type { ModuleDef, SupportTeam } from "@/features/learning/types";

export const SUPPORT: Record<string, SupportTeam> = {
  wms: {
    title: "WMS support",
    contacts: [
      { role: "Warehouse Ops Lead", name: "floor-ops@increff.demo", note: "Wrong PO / receipt issues" },
      { role: "WMS Support", name: "wms-help@increff.demo", note: "Screen errors" },
      { role: "Shift Supervisor", name: "Ops channel / radio", note: "Urgent dock decisions" },
    ],
  },
  oms: {
    title: "OMS support",
    contacts: [
      { role: "OMS Config Owner", name: "oms-config@increff.demo", note: "Location type / timezone" },
      { role: "Master Data", name: "masterdata@increff.demo", note: "Address corrections" },
      { role: "On-call L2", name: "l2-support@increff.demo", note: "System outages" },
    ],
  },
};

export const GLOSSARY: Record<string, string> = {
  "Gate Entry": "Acknowledgement of inward goods before GRN — invoice and logistics docs against PO/STN.",
  "Inward Box": "Box code linked to a Gate Entry; required before GRN can start.",
  GRN: "Goods Receipt Note — scan box/item, QC pass/fail, move to GRN bin.",
  QC: "Quality check at GRN — pass or fail with reason before bin scan.",
  Putaway: "Store GRNed inventory into locations so stock becomes LIVE for orders.",
  Bin: "Container holding items; used in GRN QC and putaway.",
  Location: "Storage slot / rack address in the warehouse.",
  "Piece Pick": "B2C picking of individual items against released picklists.",
  "Express Picking": "Priority wave; toggle ON to see express picklists, OFF for default.",
  SLA: "Required-by / dispatch deadline used to prioritize picking.",
  Manifest: "List of AWBs handed to a transporter for a client/channel.",
  Handover: "Confirming shipments are given to the logistics partner.",
  AWB: "Air Waybill / shipping label tracking number on the packet.",
  PO: "Purchase Order from buyer to supplier.",
  STO: "Stock Transfer Order between your locations.",
  ASN: "Advance Shipping Notice from supplier.",
  LR: "Lorry Receipt from the transporter.",
  BL: "Bill of Lading for sea/shipping.",
  "E-way bill": "Electronic way bill for goods movement (India).",
  "External PO No.": "PO number on the supplier/vendor paperwork.",
  "Internal PO No.": "PO id inside your system.",
  Client: "Brand / tenant you receive or fulfill for.",
  Supplier: "Vendor or party the client receives goods from — the sender in the inward flow.",
  "Allow Excess GRN": "Supplier rule deciding whether quantity received above the PO is taken as normal stock or held separately as excess. Inward-only — a supplier concept, not a customer one.",
  "Is ASN Expected": "Rule requiring an Advance Shipment Notice before goods move — a supplier pre-alerts inward, a customer expects one before outward dispatch.",
  "Storage Inspection Required": "Rule forcing QC before stock is put away — on the way in from a supplier, or before storage bound for a customer.",
  "Cross Dock Inspection Required": "Rule forcing QC on cross-docked goods that skip storage and ship straight back out, whether inward from a supplier or outward to a customer.",
  "Cross Dock": "Receiving goods and dispatching them immediately, without long-term storage.",
  "Partner Priority": "How critical a supplier or customer is, 1 to 5 — 1 most critical, 5 least.",
  "Fulfillment Location": "The client's own warehouse, store or site that OMS receives into and ships from.",
  "Partner Location": "A supplier or customer address — where goods come from or go to. The counterparty to a fulfillment location.",
  "Partner Code": "Identifies the external party itself — the supplier on inward, the customer on outward.",
  "Partner Location Code": "Identifies one specific branch, factory or store belonging to that partner.",
  "Location Code": "Identifies the client's own fulfillment location in a transaction.",
  Customer: "Party the client ships goods to — the receiver in the outward flow.",
  GSTIN: "Goods and Services Tax Identification Number held against a specific location (India); its first two digits encode the state.",
  "Location Type": "Warehouse, Store, USP, or WMS2.",
  Warehouse: "Location type where stock is received, stored, picked, packed and shipped.",
  Store: "Retail store used as a fulfillment location so online orders can ship from shop stock.",
  WMS2: "Location type for a warehouse whose floor operations run through a linked WMS instance.",
  USP: "Vendor / secondary fulfillment setup — stock sits with a vendor but OMS can still expose and allocate it.",
  SFS: "Ship-from-Store — fulfilling online orders out of retail store inventory.",
  "Client Location Mapping": "Link between a client and the fulfillment locations it is allowed to use; without it orders will not route there.",
  Category: "PRIMARY or SECONDARY site role.",
  Channel: "Sales channel (e.g. Amazon, Flipkart).",
  "PAN No.": "Permanent Account Number — mandatory tax ID captured when creating a client.",
  "Mark as Perishable": "Client flag for expiry / shelf-life goods; enables batch and expiry handling during GRN and picking.",
  "Pack Box Attributes": "Client-level packing rules — which box details (dimensions, SKU, weight) packers must capture.",
  "Primary Routing Algorithm": "Main rule OMS uses to decide which location fulfills an order.",
  "Minimize Distance": "Routing that picks the nearest location holding stock — faster delivery, lower freight.",
  "Minimize Shipments": "Routing that picks the location covering the most items — fewer parcels for the customer.",
  "Secondary Allocation Method": "Fallback logic (PRIMARY / SECONDARY / PRIMARY_AND_SECONDARY) used when the primary location cannot fulfill everything.",
  "Linked Parties": "Suppliers and customers mapped to a client.",
  "Product / SKU": "The ID card of every item OMS/WMS handles — a SKU is one specific sellable variant of a product (e.g. TSHIRT-BLK-M).",
  "SKU Code": "The unique identifier for a SKU, used across product master, inward, outward, inventory, picking, packing and reports.",
  "Bundled SKU": "A virtual combo SKU with no physical stock of its own; its sellable quantity is limited by whichever child SKU has the least stock. GRN and picking happen on the child SKUs, never the bundle.",
  "UOM (Unit of Measure)": "Defines how a larger packing unit breaks into smaller ones, e.g. one Case = 5 Boxes, one Box = 10 Each.",
  "Perishable SKU": "A SKU with expiry or shelf life (food, cosmetics, medicines) that needs batch/expiry tracking during inward and outward flows.",
  "Standard SKU Attribute": "A default SKU field created automatically for every client — Brand, MRP, Size, Category, and similar. Some are locked and cannot be reconfigured.",
  "Custom SKU Attribute": "An extra SKU field the client defines from the Attributes Configuration screen — up to 15 per client, keyed Attribute1 through Attribute15.",
  "Displayable Attribute": "Whether an attribute shows on WMS screens (GRN, QC, picking, packing) wherever SKU master data appears. Capped at 10 normal attributes; dimensions have separate headroom.",
  "Highlighted Attribute": "An attribute visually emphasized in WMS. Capped at 2, and only available for attributes that are already displayable.",
  "Searchable Attribute": "A custom SKU attribute usable to search during GRN instead of Client SKU ID. Only Attribute1 through Attribute5 can ever be searchable — a fixed rule tied to the key, not a raisable count.",
  "SKU Dimensions": "Length, breadth, height and weight captured against a SKU. Length/breadth/height are all-or-nothing together; weight is independent. Capturing a value here does not display it in WMS on its own — that still needs Attributes Configuration.",
};

export const MODULES: ModuleDef[] = [
  {
    id: "wms",
    track: "WMS",
    number: 1,
    title: "Gate Entry",
    description: "Search entries → select a PO → create and submit a gate entry.",
    href: "/wms/gate-entry",
    duration: "15–20 min",
    skills: ["Search & filter gate entries", "Select the right PO", "Fill create form", "Submit the entry"],
  },
  {
    id: "wms-receive",
    track: "WMS",
    number: 2,
    title: "Receive Inward Boxes",
    description: "Print or scan box codes for a Gate Entry, then Confirm so GRN can start.",
    href: "/wms/receive-boxes",
    duration: "8–12 min",
    skills: [
      "Choose internal vs external codes",
      "Enter Gate Entry & box count",
      "Print / scan boxes",
      "Confirm all boxes received",
    ],
  },
  {
    id: "wms-grn",
    track: "WMS",
    number: 3,
    title: "GRN",
    description: "Scan inward box → barcode → Item ID → QC bin to complete goods receipt.",
    href: "/wms/grn",
    duration: "12–15 min",
    skills: ["Scan inward box & barcode", "Scan Item ID", "QC pass / fail", "Scan QC bin"],
  },
  {
    id: "wms-putaway",
    track: "WMS",
    number: 4,
    title: "Put Away",
    description: "Bin Putaway, Bin Transfer, or Item Putaway to make inventory LIVE.",
    href: "/wms/putaway",
    duration: "10–15 min",
    skills: [
      "Pick putaway method",
      "Bin Putaway to empty location",
      "Bin Transfer to static bin",
      "Item Putaway per piece",
    ],
  },
  {
    id: "wms-pick-pending",
    track: "WMS",
    number: 5,
    title: "Piece Pick Pending",
    description: "Monitor zone / aisle pendency and decide where to send pickers.",
    href: "/wms/pick-pending",
    duration: "8–12 min",
    skills: ["Monitor zone / aisle pendency", "Assign by SLA & status", "Review Express vs Default"],
  },
  {
    id: "wms-pick-item",
    track: "WMS",
    number: 6,
    title: "Piece Pick Item",
    description: "Scan location and item, confirm pick or mark Not Found.",
    href: "/wms/pick-item",
    duration: "8–12 min",
    skills: ["Scan location & item", "Confirm pick / Not Found", "Match Express toggle to wave"],
  },
  {
    id: "wms-packing",
    track: "WMS",
    number: 7,
    title: "Piece Packing",
    description: "Scan items, complete packing, print invoice/label, scan AWB.",
    href: "/wms/packing",
    duration: "8–12 min",
    skills: ["Scan & complete packing", "Print invoice & scan AWB"],
  },
  {
    id: "wms-manifest",
    track: "WMS",
    number: 8,
    title: "Manifest",
    description: "Create or search manifests, scan AWBs, close and print.",
    href: "/wms/manifests",
    duration: "8–12 min",
    skills: ["Create / close manifest", "Print manifest for the dock"],
  },
  {
    id: "wms-handover",
    track: "WMS",
    number: 9,
    title: "Handover",
    description: "Hand shipments to the transporter by manifest or individual AWB.",
    href: "/wms/handover",
    duration: "8–12 min",
    skills: ["Load manifest or AWBs", "Remove rejected AWBs", "Confirm handover"],
  },
  {
    id: "oms-client",
    track: "OMS",
    number: 10,
    title: "Client Creation & Routing",
    description: "Add a client, then configure its Primary Routing Algorithm.",
    href: "/oms/clients",
    duration: "12–15 min",
    skills: [
      "Add a new client",
      "Set perishable & pack box flags",
      "Submit with required fields",
      "Configure Primary Routing Algorithm",
    ],
  },
  {
    id: "oms",
    track: "OMS",
    number: 11,
    title: "Fulfillment Locations (full flow)",
    description: "Browse and filter locations, then add one by form or many by CSV.",
    href: "/oms/fulfillment-locations",
    duration: "15–20 min",
    skills: [
      "Filter & find locations",
      "Read the directory",
      "Add a single location",
      "Bulk upload via CSV",
    ],
  },
  {
    id: "oms-client-mapping",
    track: "OMS",
    number: 12,
    title: "Client Fulfillment Location Mapping",
    description: "Link a client to the warehouses or stores it is allowed to use.",
    href: "/oms/client-location-mapping",
    duration: "12–15 min",
    skills: [
      "Search existing mappings",
      "Map a client to a location with GSTIN",
      "Set the client billing address",
      "Bulk upload via CSV",
    ],
  },
  {
    id: "oms-supplier",
    track: "OMS",
    number: 13,
    title: "Suppliers",
    description: "Add a supplier and set its inward rules — ASN, excess GRN and inspection.",
    href: "/oms/suppliers",
    duration: "15–20 min",
    skills: [
      "Search the supplier directory",
      "Add a supplier with code & priority",
      "Configure inward rules",
      "Bulk upload via CSV",
    ],
  },
  {
    id: "oms-customer",
    track: "OMS",
    number: 14,
    title: "Customers",
    description: "Add a customer and set its outward rules — ASN and inspection.",
    href: "/oms/customers",
    duration: "15–20 min",
    skills: [
      "Search the customer directory",
      "Add a customer with code & priority",
      "Configure outward rules",
      "Bulk upload via CSV",
    ],
  },
  {
    id: "oms-partner-location",
    track: "OMS",
    number: 15,
    title: "Partner Locations",
    description: "Register the supplier or customer address used as the source or destination of a movement.",
    href: "/oms/partner-locations",
    duration: "15–20 min",
    skills: [
      "Search by partner or Location ID",
      "Add a partner location with GSTIN",
      "Set shipping & billing addresses",
      "Bulk upload via CSV",
    ],
  },
  {
    id: "oms-product",
    track: "OMS",
    number: 16,
    title: "Product Settings",
    description: "Create, edit and configure SKUs — bundled combos, UOM breakdowns, and perishable batches.",
    href: "/oms/products",
    duration: "20–25 min",
    skills: [
      "Bulk-create SKUs via CSV",
      "Bulk-edit existing SKUs",
      "Enable perishable / batch tracking",
      "Define bundled and UOM SKUs",
    ],
  },
];

export function getModule(id: string): ModuleDef | undefined {
  return MODULES.find((m) => m.id === id);
}

export function getSupport(track: string): SupportTeam {
  return SUPPORT[track.toLowerCase()] || SUPPORT.wms;
}

export function getGlossaryEntries(keys?: string[]): [string, string][] {
  const entries = Object.entries(GLOSSARY);
  if (!keys || keys.length === 0) return entries;
  return entries.filter(([k]) => keys.includes(k));
}
