import type { TourConfig } from "@/features/learning/types";
import { getModule } from "@/shared/lib/curriculum";
import { fillInput } from "@/shared/lib/tour-utils";

const HOME = "/";
const mod = getModule("oms-customer")!;

/** Reveal the CSV field list without toggling it shut if it is already open. */
function openCsvFields() {
  const panel = document.getElementById("cust-fields-panel");
  if (panel?.classList.contains("hidden")) {
    document.getElementById("cust-btn-fields")?.click();
  }
}

export const CustomersTour: TourConfig = {
  moduleId: "oms-customer",
  pageKey: "oms-customer",
  pageHref: "/oms/customers",
  parentModuleName: "Customers",
  track: "OMS",
  number: mod.number,
  title: mod.title,
  skills: mod.skills,
  homeHref: HOME,
  glossaryKeys: [
    "Customer",
    "Client",
    "Supplier",
    "Partner Location",
    "ASN",
    "Is ASN Expected",
    "Storage Inspection Required",
    "Cross Dock Inspection Required",
    "Cross Dock",
    "Partner Priority",
  ],
  pitfalls: [
    "Confusing customer (receives goods out) with supplier (sends goods in)",
    "Leaving Is ASN Expected TRUE for a customer that never asks for one — dispatch stalls waiting on it",
    "Turning on inspection but leaving the minimum percentages blank",
    "Creating the customer but never creating its store or DC as a partner location",
    "CSV priority outside 1–5, or missing a mandatory column",
  ],
  scenarios: [
    {
      id: "add-one",
      title: "Add one customer",
      story:
        "ABC Fashion is signing RetailMart as a retail partner. Search first, then create the customer and set its outward rules — QC before dispatch, no ASN needed.",
    },
    {
      id: "bulk",
      title: "Bulk upload customers",
      story:
        "A distributor deal brings 150 retail partners at once. Use the Bulk Upload tab and load them in one CSV.",
    },
  ],
  summary: {
    title: "Customers — complete",
    intro: "You registered a customer and configured the rules that govern how goods are dispatched to it.",
    takeaways: [
      "Customer = who receives goods out; supplier = who sends goods in",
      "Is ASN Expected makes the client pre-announce shipments so the customer can prepare to receive",
      "Inspection flags force QC before dispatch — in normal storage flow, or on cross-dock goods shipped straight out",
      "Customers have no Allow Excess GRN — that rule only exists on the inward side",
    ],
    recap: [
      "Outward flow: client fulfillment location → customer partner location",
      "Priority 1 is most critical, 5 least",
      "Each customer's store or DC still needs its own partner location",
      "Bulk CSV takes up to 3000 rows; check the 20-field template first",
    ],
  },
  quiz: [
    {
      question: "ABC Fashion ships to RetailMart and buys from XYZ Garments. Who is the customer?",
      choices: ["ABC Fashion", "XYZ Garments", "RetailMart", "The transporter"],
      answer: 2,
      explain: "The customer receives goods from the client. XYZ Garments is the supplier; ABC Fashion is the client.",
    },
    {
      question: "Which configuration exists for suppliers but NOT for customers?",
      choices: ["Is ASN Expected", "Storage Inspection Required", "Allow Excess GRN", "Cross Dock Inspection Required"],
      answer: 2,
      explain: "Allow Excess GRN handles over-receipt on the inward side — customers have no equivalent outward rule.",
    },
    {
      question: "Is ASN Expected for a customer means…",
      choices: [
        "The customer inspects goods themselves",
        "The client must send shipment details before or with dispatch",
        "The customer pays in advance",
        "Excess stock is accepted automatically",
      ],
      answer: 1,
      explain: "It lets the customer prepare to receive and reconcile the incoming shipment.",
    },
    {
      question: "Goods are dispatched to a customer without being stored first. QC on that needs…",
      choices: [
        "Storage Inspection Required",
        "Cross Dock Inspection Required",
        "Is ASN Expected",
        "No setting — cross-dock skips QC",
      ],
      answer: 1,
      explain: "Cross Dock Inspection Required forces QC even when stock never goes into storage before dispatch.",
    },
    {
      question: "In the customer CSV, how many fields are there compared to the supplier CSV?",
      choices: ["One more", "The same", "One fewer", "Twice as many"],
      answer: 2,
      explain: "20 versus 21 — customers drop allowExcessGrn since it is an inward-only concept.",
    },
  ],
  steps: [
    {
      element: "#cust-search-bar",
      title: "Customers",
      description:
        "A <strong>customer</strong> is who the client ships goods to — the party receiving on the outward side. Not to be confused with a supplier, who sends goods in.",
      expected: { type: "action" },
      side: "bottom",
      skillLabel: "Search",
      skillIndex: 1,
    },
    {
      element: "#cust-search-by",
      title: "Search By",
      description:
        "Pick which field to search on — <strong>Customer Code</strong>, <strong>Customer ID</strong> or <strong>Customer Name</strong>.",
      practicePrompt: "Customer Name",
      expected: { type: "select", selector: "#cust-search-by", value: "customer-name" },
      skillLabel: "Search",
      skillIndex: 1,
    },
    {
      element: "#cust-search-value",
      title: "Search value",
      description: "Check whether this retail partner already exists before creating it. Example: <strong>RetailMart</strong>",
      practicePrompt: "RetailMart",
      expected: { type: "input", selector: "#cust-search-value", value: "RetailMart" },
      commonMistakes: "Creating a duplicate customer because nobody searched first.",
      skillLabel: "Search",
      skillIndex: 1,
    },
    {
      element: "#cust-btn-search",
      title: "Search",
      description: "Runs the query. <strong>Page Size</strong> controls how many rows come back per page.",
      expected: { type: "action" },
      skillLabel: "Search",
      skillIndex: 1,
    },
    {
      element: "#cust-results-table",
      title: "The directory",
      description:
        "The list shows the outward rules at a glance — ASN and inspection — plus <strong>Priority</strong>. <strong>View Locations</strong> opens the customer's partner locations, its actual stores and DCs.",
      expected: { type: "action" },
      side: "top",
      skillLabel: "Search",
      skillIndex: 2,
    },
    {
      element: "#cust-btn-add",
      title: "Add Customer",
      description: "Opens the create dialog. Click <strong>Next</strong> to continue inside it.",
      expected: { type: "action" },
      openModalOnNext: "modal-add-customer",
      skillLabel: "Create",
      skillIndex: 2,
    },

    // ---- Scenario split ----
    {
      element: "#modal-add-customer-tabs",
      title: "Two ways in",
      description:
        "<strong>Add New Customer</strong> creates one retail partner by hand. <strong>Bulk Upload</strong> takes a CSV. We are onboarding a single partner, so stay on the form.",
      expected: { type: "action" },
      side: "bottom",
      skillLabel: "Create",
      skillIndex: 2,
      scenarioIds: ["add-one"],
    },
    {
      element: "#modal-add-customer-tabs",
      title: "Two ways in",
      description:
        "150 retail partners one at a time is not realistic — switch to <strong>Bulk Upload</strong> and load them from a CSV.",
      expected: { type: "action" },
      switchTabOnNext: "#tab-bulk-customer",
      side: "bottom",
      skillLabel: "Bulk",
      skillIndex: 2,
      scenarioIds: ["bulk"],
    },

    // ---- Single customer form ----
    {
      element: "#field-cust-name",
      title: "Name *",
      description: "Required. The retail partner's business name. Example: <strong>RetailMart</strong>",
      practicePrompt: "RetailMart",
      required: true,
      expected: { type: "input", selector: "#cust-name", value: "RetailMart" },
      side: "right",
      skillLabel: "Create",
      skillIndex: 2,
      scenarioIds: ["add-one"],
    },
    {
      element: "#field-cust-code",
      title: "Customer Code *",
      description:
        "Required and unique. This is what outward orders quote, so use the code sales already uses. Example: <strong>RM-123456</strong>",
      practicePrompt: "RM-123456",
      required: true,
      expected: { type: "input", selector: "#cust-code", value: "RM-123456" },
      side: "bottom",
      skillLabel: "Create",
      skillIndex: 2,
      scenarioIds: ["add-one"],
    },
    {
      element: "#field-cust-priority",
      title: "Priority",
      description:
        "How critical this customer is: <strong>1 is most critical, 5 least</strong>. Defaults to 3. RetailMart is a strategic account, so set <strong>1</strong>.",
      practicePrompt: "1",
      expected: { type: "select", selector: "#cust-priority", value: "1" },
      side: "left",
      skillLabel: "Create",
      skillIndex: 2,
      scenarioIds: ["add-one"],
    },
    {
      element: "#field-cust-asn",
      title: "Is ASN Expected *",
      description:
        "Whether the client must pre-announce a shipment before or with dispatch, so the customer can prepare to receive it. RetailMart does not ask for one — pick <strong>FALSE</strong>.",
      practicePrompt: "FALSE",
      required: true,
      commonMistakes: "Setting TRUE for a customer that never asks for an ASN — dispatch then waits on a document nobody needs.",
      expected: { type: "radio", name: "cust-asn", value: "FALSE" },
      side: "right",
      skillLabel: "Outward rules",
      skillIndex: 3,
      scenarioIds: ["add-one"],
    },
    {
      element: "#field-cust-storage-insp",
      title: "Storage Inspection Required *",
      description:
        "Forces QC in the normal storage flow before goods for this customer are dispatched. Pick <strong>TRUE</strong> — watch the percentage box to its right unlock.",
      practicePrompt: "TRUE",
      required: true,
      expected: { type: "radio", name: "cust-storage-insp", value: "TRUE" },
      side: "bottom",
      skillLabel: "Outward rules",
      skillIndex: 3,
      scenarioIds: ["add-one"],
    },
    {
      element: "#cust-storage-min-pct",
      title: "Min. Storage Inspect %",
      description: "Only editable because inspection is ON. How much of the consignment must be checked. Example: <strong>10</strong>",
      practicePrompt: "10",
      expected: { type: "input", selector: "#cust-storage-min-pct", value: "10" },
      onWatchFill: () => fillInput("#cust-storage-pass-pct", "95"),
      side: "left",
      skillLabel: "Outward rules",
      skillIndex: 3,
      scenarioIds: ["add-one"],
    },
    {
      element: "#cust-storage-pass-pct",
      title: "Min. Storage Inspect Pass %",
      description: "The share of inspected items that must pass for the batch to clear. Example: <strong>95</strong>",
      expected: { type: "action" },
      commonMistakes: "Turning inspection on but leaving this blank.",
      side: "right",
      skillLabel: "Outward rules",
      skillIndex: 3,
      scenarioIds: ["add-one"],
    },
    {
      element: "#field-cust-crossdock-insp",
      title: "Cross Dock Inspection Required *",
      description:
        "Forces QC even when goods for this customer skip storage and dispatch straight out. RetailMart does not cross-dock — leave <strong>FALSE</strong>.",
      practicePrompt: "FALSE",
      required: true,
      expected: { type: "radio", name: "cust-crossdock-insp", value: "FALSE" },
      side: "bottom",
      skillLabel: "Outward rules",
      skillIndex: 3,
      scenarioIds: ["add-one"],
    },
    {
      element: "#cust-contact-name",
      title: "Contact Name *",
      description: "Required. Who to chase about a delayed or short delivery. Example: <strong>Anjali Rao</strong>",
      practicePrompt: "Anjali Rao",
      required: true,
      expected: { type: "input", selector: "#cust-contact-name", value: "Anjali Rao" },
      side: "right",
      skillLabel: "Address",
      skillIndex: 4,
      scenarioIds: ["add-one"],
    },
    {
      element: "#cust-contact-more",
      title: "Contact Email / Number",
      description: "Both optional but worth filling — dispatch and ASN queries go here.",
      practicePrompt: "anjali@retailmart.in",
      expected: { type: "input", selector: "#cust-contact-email", value: "anjali@retailmart.in" },
      onWatchFill: () => fillInput("#cust-contact-number", "+91-9845098450"),
      side: "left",
      skillLabel: "Address",
      skillIndex: 4,
      scenarioIds: ["add-one"],
    },
    {
      element: "#cust-address1",
      title: "Address Line 1 *",
      description: "Required. Example: <strong>Shop 5, MG Road</strong>",
      practicePrompt: "Shop 5, MG Road",
      required: true,
      expected: { type: "input", selector: "#cust-address1", value: "Shop 5, MG Road" },
      side: "right",
      skillLabel: "Address",
      skillIndex: 4,
      scenarioIds: ["add-one"],
    },
    {
      element: "#cust-address-more",
      title: "Address Line 2 / Area",
      description: "Both optional. Example area: <strong>Indiranagar</strong>",
      practicePrompt: "Indiranagar",
      expected: { type: "input", selector: "#cust-area", value: "Indiranagar" },
      side: "left",
      skillLabel: "Address",
      skillIndex: 4,
      scenarioIds: ["add-one"],
    },
    {
      element: "#cust-city",
      title: "City *",
      description: "Required. Example: <strong>Pune</strong>",
      practicePrompt: "Pune",
      required: true,
      expected: { type: "input", selector: "#cust-city", value: "Pune" },
      side: "right",
      skillLabel: "Address",
      skillIndex: 4,
      scenarioIds: ["add-one"],
    },
    {
      element: "#cust-pincode",
      title: "Pincode *",
      description: "Required. Example: <strong>411001</strong>",
      practicePrompt: "411001",
      required: true,
      expected: { type: "input", selector: "#cust-pincode", value: "411001" },
      side: "top",
      skillLabel: "Address",
      skillIndex: 4,
      scenarioIds: ["add-one"],
    },
    {
      element: "#cust-country",
      title: "Country *",
      description: "Required, and pick it before State. Example: <strong>India</strong>",
      practicePrompt: "India",
      required: true,
      expected: { type: "select", selector: "#cust-country", value: "IN" },
      side: "left",
      skillLabel: "Address",
      skillIndex: 4,
      scenarioIds: ["add-one"],
    },
    {
      element: "#cust-state",
      title: "State *",
      description: "Required. Example: <strong>Maharashtra</strong>",
      practicePrompt: "Maharashtra",
      required: true,
      expected: { type: "select", selector: "#cust-state", value: "MH" },
      side: "right",
      skillLabel: "Address",
      skillIndex: 4,
      scenarioIds: ["add-one"],
    },
    {
      element: "#modal-add-customer-actions",
      title: "Submit",
      description:
        "Creates the customer and issues its Customer ID. Next you would add its store or DC as a <strong>partner location</strong>, then it can be used on an outward order.",
      expected: { type: "action" },
      onWatchFill: () => {
        document.getElementById("cust-btn-submit")?.click();
      },
      side: "top",
      skillLabel: "Address",
      skillIndex: 4,
      scenarioIds: ["add-one"],
    },

    // ---- Bulk upload ----
    {
      element: "#cust-bulk-panel",
      title: "Upload Customer(s)",
      description: "One CSV registers many retail partners at once — the normal route after a distributor deal.",
      expected: { type: "action" },
      side: "bottom",
      skillLabel: "Bulk",
      skillIndex: 3,
      scenarioIds: ["bulk"],
    },
    {
      element: "#cust-bulk-file",
      title: "Choose file",
      description: "Use <strong>Browse</strong> to pick the filled-in CSV.",
      expected: { type: "action" },
      onWatchFill: () => {
        document.getElementById("cust-btn-browse")?.click();
      },
      side: "bottom",
      skillLabel: "Bulk",
      skillIndex: 3,
      scenarioIds: ["bulk"],
    },
    {
      element: "#cust-bulk-note",
      title: "Priority in the CSV",
      description:
        "The priority column takes <strong>1 to 5 only</strong> — 1 most critical, 5 least. Any other value is rejected.",
      expected: { type: "action" },
      side: "bottom",
      skillLabel: "Bulk",
      skillIndex: 3,
      scenarioIds: ["bulk"],
    },
    {
      element: "#cust-bulk-limit",
      title: "Row limit & template",
      description:
        "Up to <strong>3000 rows</strong> per upload. Always start from <strong>Download Template</strong>, and use the <strong>i</strong> icon to see what each column means.",
      expected: { type: "action" },
      onEnter: openCsvFields,
      side: "bottom",
      skillLabel: "Bulk",
      skillIndex: 4,
      scenarioIds: ["bulk"],
    },
    {
      element: "#cust-fields-panel",
      title: "The 20 CSV fields",
      description:
        "One fewer than the supplier template — there is no <strong>allowExcessGrn</strong>, since over-receipt is an inward-only concept. Everything else — ASN, both inspection flags, and their percentages — carries over.",
      expected: { type: "action" },
      onEnter: openCsvFields,
      commonMistakes: "Copying a supplier CSV and forgetting to drop the allowExcessGrn column — the row is rejected.",
      side: "top",
      skillLabel: "Bulk",
      skillIndex: 4,
      scenarioIds: ["bulk"],
    },
    {
      element: "#modal-bulk-customer-actions",
      title: "Upload",
      description:
        "Submits the file. Rejected rows come back with a reason — fix just those and re-upload. Each customer still needs its partner locations before it can be used on an outward order.",
      expected: { type: "action" },
      onWatchFill: () => {
        document.getElementById("cust-btn-upload")?.click();
      },
      side: "top",
      skillLabel: "Bulk",
      skillIndex: 4,
      scenarioIds: ["bulk"],
    },
  ],
};
